version: '3.8'

services:
  simple-web:
    image: devopsdockeruh/simple-web-service
    build: .
    volumes:
      - ./text.log:/usr/src/app/text.log
    ports:
      - 8080:8080
    container_name: simple-web
    command: ["docker", "run", "-p", "8080:8080", "simple-web", "server"]

