version: '3.8'
services:

    backend:
        image: backend
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
        depends_on:
            - db
        command: ["./server"]

    frontend:
        image: frontend
        command: ["serve","-s","-l","5000","build"]

    redis:
        image: redis

    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./database:/var/lib/postgresql/data

    proxy:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - backend
            - frontend
        ports:
            - 80:80
